services:

  jenkins:
    # image: docker.io/jenkins/jenkins-podman:latest
    image: jenkins-podman:latest  # Costume
    # build: ./Dockerfile
    container_name: jenkins-podman
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      # Mount the host's rootless Podman socket
      - /run/user/${UID}/podman/podman.sock:/run/podman/podman.sock:rw
      - ~/jenkins_key:/tmp/jenkins_key:ro   # 👈 mount HERE instead
    environment:
      - CONTAINER_HOST=unix:///run/podman/podman.sock
    security_opt:
      - label=disable
    # Optional but recommended
    user: "1000:1000"   # Run as jenkins user (UID 1000) — matches your container
    restart: unless-stopped

volumes:
  jenkins_home:
    name: jenkins_home
    driver: local
